frase = input('Digite sua frase: ')
espacos = frase.count(' ')
a = frase.count('a')
e = frase.count('e')
i = frase.count('i')
o = frase.count('o')
u = frase.count('u')
print(f'A frase tem: \n{espacos} espaços\n{a} As\n{e} Es\n{i} Is\n{o} Os\n{u} Us')